version: '3.8'
services:
  db:
    container_name: db-app-seata
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: seata_demo
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - ./v/db-data:/var/lib/mysql
